Expats/Models/List.cs
using System;
using System.Collections.Generic;

namespace Expats.Models
{
    public partial class List
    {
        public List()
        {
            Details = new HashSet<Details>();
        }

        public int Id { get; set; }
        public int Idcategory { get; set; }
        public int? Idsubcategory { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }

        public Categories IdcategoryNavigation { get; set; }
        public SubCategories IdsubcategoryNavigation { get; set; }
        public ICollection<Details> Details { get; set; }
    }
}

Expats/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Expats.Models;
using Microsoft.AspNetCore.Mvc;

namespace Expats.Controllers
{

    public class DetailsController : Controller
    {
        ExpatsDatabaseContext entities;

        public DetailsController()
        {
            entities = new ExpatsDatabaseContext();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllDetails(int id)
        {
            var rez = entities.Details.Where(s => s.Idlist == id).FirstOrDefault();


            if (rez == null)
            {
                return View("NoCategories");
            }
            else
            {
                return View(rez);

            }
        }
    }
}

Expats/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Expats.Models;

namespace Expats.Controllers
{
    public class ListController : Controller
    {
        ExpatsDatabaseContext entities;

        public ListController()
        {
            entities = new ExpatsDatabaseContext();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AllList(int id)
        {
            List<Models.List> lista = new List<Models.List>();
            var rez = entities.List.Where(s => s.Idsubcategory == id).ToList();

            foreach (var s in rez)
            {
                lista.Add(s);
            }

            return View(lista);
        }
    }
}

Expats/Views/List/AllList.cshtml
@model IEnumerable<Expats.Models.List>
@{
    ViewData["Title"] = "AllList";
}

<!DOCTYPE HTML>

<html>
<head>
    <title>AllCategories</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link href="~/css/main.css" rel="stylesheet" />
    <noscript>
        <link href="~/css/noscript.css" rel="stylesheet" />
    </noscript>
</head>
<body class="is-preload">
    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        <header id="header">
            <div class="inner">



                @*<!-- Nav -->
                <nav>
                    <ul>
                        <li><a href="#menu">Menu</a></li>
                    </ul>
                </nav>

            </div>
        </header>

        <!-- Menu -->
        <nav id="menu">
            <h2>Menu</h2>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="generic.html">Ipsum veroeros</a></li>
                <li><a href="generic.html">Tempus etiam</a></li>
                <li><a href="generic.html">Consequat dolor</a></li>
                <li><a href="elements.html">Elements</a></li>
            </ul>
        </nav>*@


                <!-- Main -->
                <div id="main">
                    <div class="inner">
                        @*<header>
                    <h1>
                        This is Phantom, a free, fully responsive site<br />
                        template designed by <a href="http://html5up.net">HTML5 UP</a>.
                    </h1>
                    <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
                </header>*@
                        <section class="tiles">
                            @foreach (var lista in Model)
                            {
                                string ime = lista.Name + ".png";

                                <article class="style1">
                                    <span class="image">
                                        <img src="~/images/list/@ime" alt="" />
                                    </span>

                                    <a href="@Url.Action( "AllDetails", "Details", new {id = lista.Id }, null)">
                                        <h2>@lista.Name</h2>

                                    </a>


                                </article>



                            }
                        </section>

                    </div>
                </div>
                <hr />
                <footer style="margin:0px 0px 32px; font-family:Arial, Helvetica, sans-serif; font-size:16px;">
                    <p>&copy; 2020 - Expats</p>
                </footer>

            </div>

            <!-- Scripts -->
            <script src="~/js/breakpoints.min.js"></script>
            <script src="~/js/browser.min.js"></script>
            <script src="~/js/jquery.min.js"></script>
            <script src="~/js/main.js"></script>
            <script src="~/js/util.js"></script>
</body>
</html>