Expats/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Expats.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Expats.Controllers
{

    public class CategoriesController : Controller
    {
        public ExpatsDatabaseContext entities;

        public CategoriesController()
        {
            entities = new ExpatsDatabaseContext();
        }
        public IActionResult Index()
        {
            return View();
        }
        
        
        public IEnumerable<Categories> All()
        {
            List<Categories> lista = new List<Categories>();
           foreach(Categories c in entities.Categories)
            {
                lista.Add(c);
            }

            return lista;
        }

        public IActionResult AllCategories()
        {       
                return View(All());  
        }
    }
}

Expats/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Expats.Models;
using Microsoft.AspNetCore.Mvc;

namespace Expats.Controllers
{
    public class SubCategoriesController : Controller
    {
        ExpatsDatabaseContext entitites;

        public SubCategoriesController()
        {
            entitites = new ExpatsDatabaseContext();
        }
        public IActionResult Index()
        {
            return View();
        }

       
        public IActionResult AllSubCategories(int id)
        {
            List<SubCategories> lista = new List<SubCategories>();
            var rez = entitites.SubCategories.Where(s => s.Idcategory == id).ToList();

            foreach(var s in rez)
            {
                lista.Add(s);
            }

            return View(lista);
        }
    }
}

Expats/Views/Categories/AllCategories.cshtml
@model IEnumerable<Expats.Models.Categories>
@{
    ViewData["Title"] = "AllCategories";
}


<!DOCTYPE HTML>

<html>
<head>
    <title>AllCategories</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link href="~/css/main.css" rel="stylesheet" />
    <noscript>
        <link href="~/css/noscript.css" rel="stylesheet" />
    </noscript>
</head>
<body class="is-preload">
    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        <header id="header">
            <div class="inner">



                @*<!-- Nav -->
                <nav>
                    <ul>
                        <li><a href="#menu">Menu</a></li>
                    </ul>
                </nav>

            </div>
        </header>

        <!-- Menu -->
        <nav id="menu">
            <h2>Menu</h2>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="generic.html">Ipsum veroeros</a></li>
                <li><a href="generic.html">Tempus etiam</a></li>
                <li><a href="generic.html">Consequat dolor</a></li>
                <li><a href="elements.html">Elements</a></li>
            </ul>
        </nav>*@


                <!-- Main -->
                <div id="main">
                    <div class="inner">
                        @*<header>
                    <h1>

                    </h1>
                    <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
                </header>*@
                        <section class="tiles">
                            @foreach (var kategorija in Model)
                            {
                                string ime = kategorija.Name + ".png";

                                <article class="style1">
                                    <span class="image">
                                        <img src="../images/categories/@ime" alt="" />
                                    </span>



                                    <a href="@Url.Action( "AllSubCategories", "SubCategories", new {id = kategorija.Id }, null)">
                                        <h2>@kategorija.Name</h2>

                                    </a>


                                </article>



                            }
                        </section>

                    </div>
                </div>
                <hr />
                <footer style="margin:0px 0px 32px; font-family:Arial, Helvetica, sans-serif; font-size:16px;">
                    <p>&copy; 2020 - Expats</p>
                </footer>


            </div>

    <!-- Scripts -->
    <script src="~/js/breakpoints.min.js"></script>
    <script src="~/js/browser.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/util.js"></script>
</body>
</html>